version: "2"
services:
  db_data:
    image: alpine:latest
    volumes:
      - /var/lib/postgresql/data/pgdata
    command: "true"
  db:
    build: ./db/
    image: libreforge/db
    ports:
      - "5432:5432"
    volumes_from:
      - db_data
    environment:
      - POSTGRES_DB=libreforge
      - POSTGRES_USER=libreforge
      - POSTGRES_PASSWORD=libreforge
      - PGDATA=/var/lib/postgresql/data/pgdata
  sec:
    build: ./sec/
    image: libreforge/sec
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=127.0.0.1:1234
  dev:
    build: ./dev/
    image: libreforge/back
    ports:
      - "5050:5050"
    links:
      - db:db
      - sec:sec
    volumes:
      - $DEV/libreforge/alexandria:/home/dev/alexandria
      - $HOME/.m2:/home/dev/.m2
      - $HOME/.lein:/home/dev/.lein
      - $HOME/.gradle:/home/dev/.gradle
      - $HOME/.sdkman/archives:/home/dev/.sdkman/archives
      - $HOME/.sdkman/candidates:/home/dev/.sdkman/candidates
